server:
  port: 2345
#debug: true

spring:
  application:
    name: sentinel-dashboard-plus
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/db1?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:lg123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource


mybatis:
  mapper-locations:
    - classpath:mapper/*Mapper.xml
  type-aliases-package: com.example.webapp.po
debug: true